export default [
    {
        name: 'environmentMapTexture',
        type: 'cubeTexture',
        path: [
            '/textures/environmentMap/px.jpg',
            '/textures/environmentMap/nx.jpg',
            '/textures/environmentMap/py.jpg',
            '/textures/environmentMap/ny.jpg',
            '/textures/environmentMap/pz.jpg',
            '/textures/environmentMap/nz.jpg'
        ]
    },
    {
        name: 'grassColorTexture',
        type: 'texture',
        path: '/textures/dirt/color.jpg'
    },
    {
        name: 'grassNormalTexture',
        type: 'texture',
        path: '/textures/dirt/normal.jpg'
    },
    {
        name: 'foxModel',
        type: 'gltfModel',
        path: '/models/Fox/glTF/Fox.gltf'
    },
    {
        name: 'robotModel',
        type: 'gltfModel',
        path: '/models/Robot/Robot.glb'
    },
    {
        name: 'zombieModel',
        type: 'gltfModel',
        path: '/models/Zombie/Zombie.glb'
    },
    {
        name: 'coinModel',
        type: 'gltfModel',
        path: '/models/Coin/Coin.glb'
    },
    {
        name: 'portalModel',
        type: 'gltfModel',
        path: '/models/Portal/Portal.glb'
    },
    { name: 'bed_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/bed_2_world_ap_0_lev1.glb' },
    { name: 'bed_3_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/bed_3_world_ap_0_lev1.glb' },
    { name: 'bed_4_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/bed_4_world_ap_0_lev1.glb' },
    { name: 'bed_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/bed_world_ap_0_lev1.glb' },
    { name: 'behch_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/behch_world_ap_0_lev1.glb' },
    { name: 'bench_1_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/bench_1_world_ap_0_lev1.glb' },
    { name: 'bench_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/bench_2_world_ap_0_lev1.glb' },
    { name: 'bench_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/bench_world_ap_0_lev1.glb' },
    { name: 'bushes_15_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/bushes_15_2_world_ap_0_lev1.glb' },
    { name: 'bushes_15_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/bushes_15_world_ap_0_lev1.glb' },
    { name: 'bushes_2_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/bushes_2_2_world_ap_0_lev1.glb' },
    { name: 'bushes_2_3_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/bushes_2_3_world_ap_0_lev1.glb' },
    { name: 'bushes_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/bushes_2_world_ap_0_lev1.glb' },
    { name: 'bushes_3_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/bushes_3_2_world_ap_0_lev1.glb' },
    { name: 'bushes_3_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/bushes_3_world_ap_0_lev1.glb' },
    { name: 'bushes_4_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/bushes_4_world_ap_0_lev1.glb' },
    { name: 'car_03_1_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/car_03_1_2_world_ap_0_lev1.glb' },
    { name: 'car_03_1_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/car_03_1_world_ap_0_lev1.glb' },
    { name: 'car_03_2_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/car_03_2_2_world_ap_0_lev1.glb' },
    { name: 'car_03_2_3_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/car_03_2_3_world_ap_0_lev1.glb' },
    { name: 'car_03_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/car_03_2_world_ap_0_lev1.glb' },
    { name: 'car_03_3_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/car_03_3_world_ap_0_lev1.glb' },
    { name: 'car_03_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/car_03_world_ap_0_lev1.glb' },
    { name: 'car_04_1_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/car_04_1_2_world_ap_0_lev1.glb' },
    { name: 'car_04_1_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/car_04_1_world_ap_0_lev1.glb' },
    { name: 'car_04_2_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/car_04_2_2_world_ap_0_lev1.glb' },
    { name: 'car_04_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/car_04_2_world_ap_0_lev1.glb' },
    { name: 'car_04_3_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/car_04_3_world_ap_0_lev1.glb' },
    { name: 'car_04_4_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/car_04_4_world_ap_0_lev1.glb' },
    { name: 'car_04_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/car_04_world_ap_0_lev1.glb' },
    { name: 'car_08_1_world_ap.15_0_lev1', type: 'gltfModel', path: '/models/toycar/car_08_1_world_ap.15_0_lev1.glb' },
    { name: 'car_08_2_world_ap.11_0_lev1', type: 'gltfModel', path: '/models/toycar/car_08_2_world_ap.11_0_lev1.glb' },
    { name: 'car_08_3_world_ap.9_0_lev1', type: 'gltfModel', path: '/models/toycar/car_08_3_world_ap.9_0_lev1.glb' },
    { name: 'car_08_4_world_ap.8_0_lev1', type: 'gltfModel', path: '/models/toycar/car_08_4_world_ap.8_0_lev1.glb' },
    { name: 'car_08_5_world_ap.17_0_lev1', type: 'gltfModel', path: '/models/toycar/car_08_5_world_ap.17_0_lev1.glb' },
    { name: 'car_08_6_world_ap.19_0_lev1', type: 'gltfModel', path: '/models/toycar/car_08_6_world_ap.19_0_lev1.glb' },
    { name: 'car_08_world_ap.16_0_lev1', type: 'gltfModel', path: '/models/toycar/car_08_world_ap.16_0_lev1.glb' },
    { name: 'cube_7_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/cube_7_2_world_ap_0_lev1.glb' },
    { name: 'cube_7_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/cube_7_world_ap_0_lev1.glb' },
    { name: 'firtree_1_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/firtree_1_2_world_ap_0_lev1.glb' },
    { name: 'firtree_1_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/firtree_1_world_ap_0_lev1.glb' },
    { name: 'firtree_2_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/firtree_2_2_world_ap_0_lev1.glb' },
    { name: 'firtree_2_3_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/firtree_2_3_world_ap_0_lev1.glb' },
    { name: 'firtree_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/firtree_2_world_ap_0_lev1.glb' },
    { name: 'firtree_3_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/firtree_3_2_world_ap_0_lev1.glb' },
    { name: 'firtree_3_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/firtree_3_world_ap_0_lev1.glb' },
    { name: 'firtree_4_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/firtree_4_2_world_ap_0_lev1.glb' },
    { name: 'firtree_4_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/firtree_4_world_ap_0_lev1.glb' },
    { name: 'firtree_47_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/firtree_47_2_world_ap_0_lev1.glb' },
    { name: 'firtree_47_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/firtree_47_world_ap_0_lev1.glb' },
    { name: 'firtree_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/firtree_world_ap_0_lev1.glb' },
    { name: 'floor_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/floor_2_world_ap_0_lev1.glb' },
    { name: 'floor_3_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/floor_3_world_ap_0_lev1.glb' },
    { name: 'floor_4_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/floor_4_2_world_ap_0_lev1.glb' },
    { name: 'floor_4_3_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/floor_4_3_world_ap_0_lev1.glb' },
    { name: 'floor_4_4_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/floor_4_4_world_ap_0_lev1.glb' },
    { name: 'floor_4_5_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/floor_4_5_world_ap_0_lev1.glb' },
    { name: 'floor_4_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/floor_4_world_ap_0_lev1.glb' },
    { name: 'floor_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/floor_world_ap_0_lev1.glb' },
    { name: 'house_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/house_2_world_ap_0_lev1.glb' },
    { name: 'house_3_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/house_3_world_ap_0_lev1.glb' },
    { name: 'house_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/house_world_ap_0_lev1.glb' },
    { name: 'light_1_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/light_1_2_world_ap_0_lev1.glb' },
    { name: 'light_1_3_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/light_1_3_world_ap_0_lev1.glb' },
    { name: 'light_1_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/light_1_world_ap_0_lev1.glb' },
    { name: 'light_2_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/light_2_2_world_ap_0_lev1.glb' },
    { name: 'light_2_3_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/light_2_3_world_ap_0_lev1.glb' },
    { name: 'light_2_4_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/light_2_4_world_ap_0_lev1.glb' },
    { name: 'light_2_5_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/light_2_5_world_ap_0_lev1.glb' },
    { name: 'light_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/light_2_world_ap_0_lev1.glb' },
    { name: 'light_3_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/light_3_2_world_ap_0_lev1.glb' },
    { name: 'light_3_3_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/light_3_3_world_ap_0_lev1.glb' },
    { name: 'light_3_4_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/light_3_4_world_ap_0_lev1.glb' },
    { name: 'light_3_5_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/light_3_5_world_ap_0_lev1.glb' },
    { name: 'light_3_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/light_3_world_ap_0_lev1.glb' },
    { name: 'light_4_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/light_4_2_world_ap_0_lev1.glb' },
    { name: 'light_4_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/light_4_world_ap_0_lev1.glb' },
    { name: 'light_5_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/light_5_world_ap_0_lev1.glb' },
    { name: 'light_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/light_world_ap_0_lev1.glb' },
    { name: 'muff_1_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/muff_1_world_ap_0_lev1.glb' },
    { name: 'muff_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/muff_world_ap_0_lev1.glb' },
    { name: 'road_lines_12_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/road_lines_12_world_ap_0_lev1.glb' },
    { name: 'road_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/road_world_ap_0_lev1.glb' },
    { name: 'shop_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/shop_world_ap_0_lev1.glb' },
    { name: 'traffic_light_1_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/traffic_light_1_2_world_ap_0_lev1.glb' },
    { name: 'traffic_light_1_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/traffic_light_1_world_ap_0_lev1.glb' },
    { name: 'traffic_light_2_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/traffic_light_2_2_world_ap_0_lev1.glb' },
    { name: 'traffic_light_2_3_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/traffic_light_2_3_world_ap_0_lev1.glb' },
    { name: 'traffic_light_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/traffic_light_2_world_ap_0_lev1.glb' },
    { name: 'traffic_light_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/traffic_light_world_ap_0_lev1.glb' },
    { name: 'trash_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/trash_2_world_ap_0_lev1.glb' },
    { name: 'trash_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/trash_world_ap_0_lev1.glb' },
    { name: 'tree_1_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/tree_1_2_world_ap_0_lev1.glb' },
    { name: 'tree_1_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/tree_1_world_ap_0_lev1.glb' },
    { name: 'tree_2_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/tree_2_2_world_ap_0_lev1.glb' },
    { name: 'tree_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/tree_2_world_ap_0_lev1.glb' },
    { name: 'tree_3_2_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/tree_3_2_world_ap_0_lev1.glb' },
    { name: 'tree_3_world_ap_0_lev1', type: 'gltfModel', path: '/models/toycar/tree_3_world_ap_0_lev1.glb' },
    { name: 'circle__0_lev1', type: 'gltfModel', path: '/models/toycar2/circle__0_lev1.glb' },
    { name: 'circle.001__0_lev1', type: 'gltfModel', path: '/models/toycar2/circle.001__0_lev1.glb' },
    { name: 'circle.002__0_lev1', type: 'gltfModel', path: '/models/toycar2/circle.002__0_lev1.glb' },
    { name: 'cube_material.005_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube_material.005_0_lev1.glb' },
    { name: 'cube.000_kaca.001_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.000_kaca.001_0_lev1.glb' },
    { name: 'cube.000_material.014_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.000_material.014_0_lev1.glb' },
    { name: 'cube.000_spion_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.000_spion_0_lev1.glb' },
    { name: 'cube.001_material.001_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.001_material.001_0_lev1.glb' },
    { name: 'cube.002_material.009_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.002_material.009_0_lev1.glb' },
    { name: 'cube.003_material.008_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.003_material.008_0_lev1.glb' },
    { name: 'cube.004_material.008_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.004_material.008_0_lev1.glb' },
    { name: 'cube.005_material.007_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.005_material.007_0_lev1.glb' },
    { name: 'cube.006_material.004_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.006_material.004_0_lev1.glb' },
    { name: 'cube.007_material.006_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.007_material.006_0_lev1.glb' },
    { name: 'cube.008_material.059_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.008_material.059_0_lev1.glb' },
    { name: 'cube.009_material.059_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.009_material.059_0_lev1.glb' },
    { name: 'cube.010_material.059_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.010_material.059_0_lev1.glb' },
    { name: 'cube.011_material.059_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.011_material.059_0_lev1.glb' },
    { name: 'cube.012_material.059_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.012_material.059_0_lev1.glb' },
    { name: 'cube.013_material.059_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.013_material.059_0_lev1.glb' },
    { name: 'cube.014_material.059_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.014_material.059_0_lev1.glb' },
    { name: 'cube.015__0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.015__0_lev1.glb' },
    { name: 'cube.016_material.059_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.016_material.059_0_lev1.glb' },
    { name: 'cube.017_material.008_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.017_material.008_0_lev1.glb' },
    { name: 'cube.018_material.002_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.018_material.002_0_lev1.glb' },
    { name: 'cube.019_material.008_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.019_material.008_0_lev1.glb' },
    { name: 'cube.023_material.002_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.023_material.002_0_lev1.glb' },
    { name: 'cube.024_material.002_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.024_material.002_0_lev1.glb' },
    { name: 'cube.026_material.002_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.026_material.002_0_lev1.glb' },
    { name: 'cube.028_material.059_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.028_material.059_0_lev1.glb' },
    { name: 'cube.031_material.015_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.031_material.015_0_lev1.glb' },
    { name: 'cube.032_1_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.032_1_0_lev1.glb' },
    { name: 'cube.032_2_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.032_2_0_lev1.glb' },
    { name: 'cube.033_material.016_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.033_material.016_0_lev1.glb' },
    { name: 'cube.034__0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.034__0_lev1.glb' },
    { name: 'cube.035__0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.035__0_lev1.glb' },
    { name: 'cube.036_lampu_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.036_lampu_0_lev1.glb' },
    { name: 'cube.036_material.017_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.036_material.017_0_lev1.glb' },
    { name: 'cube.036_material.018_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.036_material.018_0_lev1.glb' },
    { name: 'cube.037_kaca_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.037_kaca_0_lev1.glb' },
    { name: 'cube.037_material.019_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.037_material.019_0_lev1.glb' },
    { name: 'cube.037_mobile_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.037_mobile_0_lev1.glb' },
    { name: 'cube.038_kaca.001_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.038_kaca.001_0_lev1.glb' },
    { name: 'cube.038_material.014_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.038_material.014_0_lev1.glb' },
    { name: 'cube.038_spion_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.038_spion_0_lev1.glb' },
    { name: 'cube.039__0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.039__0_lev1.glb' },
    { name: 'cube.040__0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.040__0_lev1.glb' },
    { name: 'cube.041__0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.041__0_lev1.glb' },
    { name: 'cube.045_bank1_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.045_bank1_0_lev1.glb' },
    { name: 'cube.046_material.147_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.046_material.147_0_lev1.glb' },
    { name: 'cube.046_material.413_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.046_material.413_0_lev1.glb' },
    { name: 'cube.047_material.372_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.047_material.372_0_lev1.glb' },
    { name: 'cube.047_material.373_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.047_material.373_0_lev1.glb' },
    { name: 'cube.047_material.374_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.047_material.374_0_lev1.glb' },
    { name: 'cube.047_material.375_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.047_material.375_0_lev1.glb' },
    { name: 'cube.047_material.376_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.047_material.376_0_lev1.glb' },
    { name: 'cube.047_material.377_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.047_material.377_0_lev1.glb' },
    { name: 'cube.047_material.378_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.047_material.378_0_lev1.glb' },
    { name: 'cube.047_material.401_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.047_material.401_0_lev1.glb' },
    { name: 'cube.047_material.402_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.047_material.402_0_lev1.glb' },
    { name: 'cube.048_material.383_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.048_material.383_0_lev1.glb' },
    { name: 'cube.048_material.384_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.048_material.384_0_lev1.glb' },
    { name: 'cube.048_material.385_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.048_material.385_0_lev1.glb' },
    { name: 'cube.048_material.386_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.048_material.386_0_lev1.glb' },
    { name: 'cube.048_material.387_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.048_material.387_0_lev1.glb' },
    { name: 'cube.048_material.388_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.048_material.388_0_lev1.glb' },
    { name: 'cube.048_material.389_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.048_material.389_0_lev1.glb' },
    { name: 'cube.049_bank1_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.049_bank1_0_lev1.glb' },
    { name: 'cube.050_bank1_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.050_bank1_0_lev1.glb' },
    { name: 'cube.051_bank1_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.051_bank1_0_lev1.glb' },
    { name: 'cube.052_bank1_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.052_bank1_0_lev1.glb' },
    { name: 'cube.053_bank1_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.053_bank1_0_lev1.glb' },
    { name: 'cube.054_bank1_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.054_bank1_0_lev1.glb' },
    { name: 'cube.055_bank1_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.055_bank1_0_lev1.glb' },
    { name: 'cube.056_bank1_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.056_bank1_0_lev1.glb' },
    { name: 'cube.060_bank1_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.060_bank1_0_lev1.glb' },
    { name: 'cube.128_bank1_0_lev1', type: 'gltfModel', path: '/models/toycar2/cube.128_bank1_0_lev1.glb' },
    { name: 'cylinder.004_material.055_0_lev1', type: 'gltfModel', path: '/models/toycar2/cylinder.004_material.055_0_lev1.glb' },
    { name: 'cylinder.005_material.150_0_lev1', type: 'gltfModel', path: '/models/toycar2/cylinder.005_material.150_0_lev1.glb' },
    { name: 'cylinder.010_material.020_0_lev1', type: 'gltfModel', path: '/models/toycar2/cylinder.010_material.020_0_lev1.glb' },
    { name: 'cylinder.010_material.021_0_lev1', type: 'gltfModel', path: '/models/toycar2/cylinder.010_material.021_0_lev1.glb' },
    { name: 'cylinder.010_material.022_0_lev1', type: 'gltfModel', path: '/models/toycar2/cylinder.010_material.022_0_lev1.glb' },
    { name: 'cylinder.012_material.150_0_lev1', type: 'gltfModel', path: '/models/toycar2/cylinder.012_material.150_0_lev1.glb' },
    { name: 'cylinder.013_material.150_0_lev1', type: 'gltfModel', path: '/models/toycar2/cylinder.013_material.150_0_lev1.glb' },
    { name: 'cylinder.015_material.150_0_lev1', type: 'gltfModel', path: '/models/toycar2/cylinder.015_material.150_0_lev1.glb' },
    { name: 'text_material.353_0_lev1', type: 'gltfModel', path: '/models/toycar2/text_material.353_0_lev1.glb' },
    { name: 'text.001_material.353_0_lev1', type: 'gltfModel', path: '/models/toycar2/text.001_material.353_0_lev1.glb' },
    { name: 'text.002_material.353_0_lev1', type: 'gltfModel', path: '/models/toycar2/text.002_material.353_0_lev1.glb' },
    { name: 'text.003_material.353_0_lev1', type: 'gltfModel', path: '/models/toycar2/text.003_material.353_0_lev1.glb' },
    { name: 'text.004_material.354_0_lev1', type: 'gltfModel', path: '/models/toycar2/text.004_material.354_0_lev1.glb' },
    { name: 'object_10_lev1', type: 'gltfModel', path: '/models/toycar3/object_10_lev1.glb' },
    { name: 'object_100_lev1', type: 'gltfModel', path: '/models/toycar3/object_100_lev1.glb' },
    { name: 'object_102_lev1', type: 'gltfModel', path: '/models/toycar3/object_102_lev1.glb' },
    { name: 'object_104_lev1', type: 'gltfModel', path: '/models/toycar3/object_104_lev1.glb' },
    { name: 'object_106_lev1', type: 'gltfModel', path: '/models/toycar3/object_106_lev1.glb' },
    { name: 'object_108_lev1', type: 'gltfModel', path: '/models/toycar3/object_108_lev1.glb' },
    { name: 'object_110_lev1', type: 'gltfModel', path: '/models/toycar3/object_110_lev1.glb' },
    { name: 'object_112_lev1', type: 'gltfModel', path: '/models/toycar3/object_112_lev1.glb' },
    { name: 'object_114_lev1', type: 'gltfModel', path: '/models/toycar3/object_114_lev1.glb' },
    { name: 'object_116_lev1', type: 'gltfModel', path: '/models/toycar3/object_116_lev1.glb' },
    { name: 'object_118_lev1', type: 'gltfModel', path: '/models/toycar3/object_118_lev1.glb' },
    { name: 'object_12_lev1', type: 'gltfModel', path: '/models/toycar3/object_12_lev1.glb' },
    { name: 'object_120_lev1', type: 'gltfModel', path: '/models/toycar3/object_120_lev1.glb' },
    { name: 'object_122_lev1', type: 'gltfModel', path: '/models/toycar3/object_122_lev1.glb' },
    { name: 'object_124_lev1', type: 'gltfModel', path: '/models/toycar3/object_124_lev1.glb' },
    { name: 'object_126_lev1', type: 'gltfModel', path: '/models/toycar3/object_126_lev1.glb' },
    { name: 'object_128_lev1', type: 'gltfModel', path: '/models/toycar3/object_128_lev1.glb' },
    { name: 'object_130_lev1', type: 'gltfModel', path: '/models/toycar3/object_130_lev1.glb' },
    { name: 'object_132_lev1', type: 'gltfModel', path: '/models/toycar3/object_132_lev1.glb' },
    { name: 'object_134_lev1', type: 'gltfModel', path: '/models/toycar3/object_134_lev1.glb' },
    { name: 'object_136_lev1', type: 'gltfModel', path: '/models/toycar3/object_136_lev1.glb' },
    { name: 'object_138_lev1', type: 'gltfModel', path: '/models/toycar3/object_138_lev1.glb' },
    { name: 'object_140_lev1', type: 'gltfModel', path: '/models/toycar3/object_140_lev1.glb' },
    { name: 'object_142_lev1', type: 'gltfModel', path: '/models/toycar3/object_142_lev1.glb' },
    { name: 'object_144_lev1', type: 'gltfModel', path: '/models/toycar3/object_144_lev1.glb' },
    { name: 'object_146_lev1', type: 'gltfModel', path: '/models/toycar3/object_146_lev1.glb' },
    { name: 'object_148_lev1', type: 'gltfModel', path: '/models/toycar3/object_148_lev1.glb' },
    { name: 'object_150_lev1', type: 'gltfModel', path: '/models/toycar3/object_150_lev1.glb' },
    { name: 'object_152_lev1', type: 'gltfModel', path: '/models/toycar3/object_152_lev1.glb' },
    { name: 'object_154_lev1', type: 'gltfModel', path: '/models/toycar3/object_154_lev1.glb' },
    { name: 'object_156_lev1', type: 'gltfModel', path: '/models/toycar3/object_156_lev1.glb' },
    { name: 'object_158_lev1', type: 'gltfModel', path: '/models/toycar3/object_158_lev1.glb' },
    { name: 'object_160_lev1', type: 'gltfModel', path: '/models/toycar3/object_160_lev1.glb' },
    { name: 'object_162_lev1', type: 'gltfModel', path: '/models/toycar3/object_162_lev1.glb' },
    { name: 'object_164_lev1', type: 'gltfModel', path: '/models/toycar3/object_164_lev1.glb' },
    { name: 'object_166_lev1', type: 'gltfModel', path: '/models/toycar3/object_166_lev1.glb' },
    { name: 'object_168_lev1', type: 'gltfModel', path: '/models/toycar3/object_168_lev1.glb' },
    { name: 'object_170_lev1', type: 'gltfModel', path: '/models/toycar3/object_170_lev1.glb' },
    { name: 'object_172_lev1', type: 'gltfModel', path: '/models/toycar3/object_172_lev1.glb' },
    { name: 'object_174_lev1', type: 'gltfModel', path: '/models/toycar3/object_174_lev1.glb' },
    { name: 'object_176_lev1', type: 'gltfModel', path: '/models/toycar3/object_176_lev1.glb' },
    { name: 'object_178_lev1', type: 'gltfModel', path: '/models/toycar3/object_178_lev1.glb' },
    { name: 'object_180_lev1', type: 'gltfModel', path: '/models/toycar3/object_180_lev1.glb' },
    { name: 'object_182_lev1', type: 'gltfModel', path: '/models/toycar3/object_182_lev1.glb' },
    { name: 'object_184_lev1', type: 'gltfModel', path: '/models/toycar3/object_184_lev1.glb' },
    { name: 'object_186_lev1', type: 'gltfModel', path: '/models/toycar3/object_186_lev1.glb' },
    { name: 'object_188_lev1', type: 'gltfModel', path: '/models/toycar3/object_188_lev1.glb' },
    { name: 'object_190_lev1', type: 'gltfModel', path: '/models/toycar3/object_190_lev1.glb' },
    { name: 'object_22_lev1', type: 'gltfModel', path: '/models/toycar3/object_22_lev1.glb' },
    { name: 'object_24_lev1', type: 'gltfModel', path: '/models/toycar3/object_24_lev1.glb' },
    { name: 'object_26_lev1', type: 'gltfModel', path: '/models/toycar3/object_26_lev1.glb' },
    { name: 'object_26.001_lev1', type: 'gltfModel', path: '/models/toycar3/object_26.001_lev1.glb' },
    { name: 'object_28_lev1', type: 'gltfModel', path: '/models/toycar3/object_28_lev1.glb' },
    { name: 'object_28.001_lev1', type: 'gltfModel', path: '/models/toycar3/object_28.001_lev1.glb' },
    { name: 'object_30_lev1', type: 'gltfModel', path: '/models/toycar3/object_30_lev1.glb' },
    { name: 'object_30.001_lev1', type: 'gltfModel', path: '/models/toycar3/object_30.001_lev1.glb' },
    { name: 'object_32_lev1', type: 'gltfModel', path: '/models/toycar3/object_32_lev1.glb' },
    { name: 'object_32.001_lev1', type: 'gltfModel', path: '/models/toycar3/object_32.001_lev1.glb' },
    { name: 'object_34_lev1', type: 'gltfModel', path: '/models/toycar3/object_34_lev1.glb' },
    { name: 'object_34.001_lev1', type: 'gltfModel', path: '/models/toycar3/object_34.001_lev1.glb' },
    { name: 'object_38_lev1', type: 'gltfModel', path: '/models/toycar3/object_38_lev1.glb' },
    { name: 'object_4_lev1', type: 'gltfModel', path: '/models/toycar3/object_4_lev1.glb' },
    { name: 'object_40_lev1', type: 'gltfModel', path: '/models/toycar3/object_40_lev1.glb' },
    { name: 'object_48_lev1', type: 'gltfModel', path: '/models/toycar3/object_48_lev1.glb' },
    { name: 'object_50_lev1', type: 'gltfModel', path: '/models/toycar3/object_50_lev1.glb' },
    { name: 'object_52_lev1', type: 'gltfModel', path: '/models/toycar3/object_52_lev1.glb' },
    { name: 'object_54_lev1', type: 'gltfModel', path: '/models/toycar3/object_54_lev1.glb' },
    { name: 'object_56_lev1', type: 'gltfModel', path: '/models/toycar3/object_56_lev1.glb' },
    { name: 'object_58_lev1', type: 'gltfModel', path: '/models/toycar3/object_58_lev1.glb' },
    { name: 'object_6_lev1', type: 'gltfModel', path: '/models/toycar3/object_6_lev1.glb' },
    { name: 'object_60_lev1', type: 'gltfModel', path: '/models/toycar3/object_60_lev1.glb' },
    { name: 'object_62_lev1', type: 'gltfModel', path: '/models/toycar3/object_62_lev1.glb' },
    { name: 'object_64_lev1', type: 'gltfModel', path: '/models/toycar3/object_64_lev1.glb' },
    { name: 'object_66_lev1', type: 'gltfModel', path: '/models/toycar3/object_66_lev1.glb' },
    { name: 'object_68_lev1', type: 'gltfModel', path: '/models/toycar3/object_68_lev1.glb' },
    { name: 'object_70_lev1', type: 'gltfModel', path: '/models/toycar3/object_70_lev1.glb' },
    { name: 'object_72_lev1', type: 'gltfModel', path: '/models/toycar3/object_72_lev1.glb' },
    { name: 'object_74_lev1', type: 'gltfModel', path: '/models/toycar3/object_74_lev1.glb' },
    { name: 'object_76_lev1', type: 'gltfModel', path: '/models/toycar3/object_76_lev1.glb' },
    { name: 'object_78_lev1', type: 'gltfModel', path: '/models/toycar3/object_78_lev1.glb' },
    { name: 'object_8_lev1', type: 'gltfModel', path: '/models/toycar3/object_8_lev1.glb' },
    { name: 'object_80_lev1', type: 'gltfModel', path: '/models/toycar3/object_80_lev1.glb' },
    { name: 'object_82_lev1', type: 'gltfModel', path: '/models/toycar3/object_82_lev1.glb' },
    { name: 'object_84_lev1', type: 'gltfModel', path: '/models/toycar3/object_84_lev1.glb' },
    { name: 'object_86_lev1', type: 'gltfModel', path: '/models/toycar3/object_86_lev1.glb' },
    { name: 'object_88_lev1', type: 'gltfModel', path: '/models/toycar3/object_88_lev1.glb' },
    { name: 'object_90_lev1', type: 'gltfModel', path: '/models/toycar3/object_90_lev1.glb' },
    { name: 'object_92_lev1', type: 'gltfModel', path: '/models/toycar3/object_92_lev1.glb' },
    { name: 'object_94_lev1', type: 'gltfModel', path: '/models/toycar3/object_94_lev1.glb' },
    { name: 'object_96_lev1', type: 'gltfModel', path: '/models/toycar3/object_96_lev1.glb' },
    { name: 'object_98_lev1', type: 'gltfModel', path: '/models/toycar3/object_98_lev1.glb' }
]